// 🔹 Core sensor concepts

export enum Room {
  LIVING_ROOM = 'LIVING_ROOM',
  BEDROOM = 'BEDROOM',
  BATHROOM = 'BATHROOM',
  KITCHEN = 'KITCHEN',
  DINING_ROOM = 'DINING_ROOM',
  HALLWAY = 'HALLWAY',
  GARAGE = 'GARAGE',
  CLOFFICE = 'CLOFFICE',
  HEARTH = 'HEARTH',
  BACKYARD = 'BACKYARD',
  FRONTYARD = 'FRONTYARD',
  LEA_BEDROOM = 'LEA_BEDROOM',
  MAX_BEDROOM = 'MAX_BEDROOM'
}

export enum SensorType {
  BED_OCCUPANCY = 'BED_OCCUPANCY',
  MOTION = 'MOTION',
  CONTACT = 'CONTACT',
  TEMPERATURE = 'TEMPERATURE'
}
